### ISSUE TITLE
Timezone handling needs to be done consistently and correctly

### ISSUE THREAD

**Issue by hoylen** [digitalmethodsinitiative/dmi-tcat#197] opened 2016-05-23 00:13 UTC
How timezones are handled needs to be cleaned up.

Currently, timestamps on the HTML pages are displayed in UTC+1 (and in UTC at other times of the year), which neither matches the user's timezone (unless they are in the UK) or Twitter's universal representation in UTC. It also does not follow the server's operating system timezone.

A simple workaround **might** be to change `date_default_timezone_set` in _config.php.example_ to be "UTC" instead of "Europe/London").

Probably the best approach is not to set PHP's timezone, but to ensure all the code (including the calls between TCAT and MySQL) correctly deals with timestamps according to when they are in UTC vs the local timezone - regardless of what the operating system or MySQL's local timezone is set to.

Data in CSV/TSV format should always be in UTC. The HTML pages should either display timezones in UTC with a "Z" appended, in the local timezone of the server (with an indicator), or in the browser's timezone. The first option is the easiest, the second option is not ideal if a TCAT deployment has users are from multiple timezones, the last option involves significant implementation in client-side JavaScript.

Simply setting the timezone in _config.php_ to a local timezone is incorrect, because it causes the misinterpretation of the UTC timestamps in the tweets (as was discovered in the partially-rejected pull-request #194). Maybe "Europe/London" is already causing tweet timestamps to be misinterpreted (but no one has noticed the one hour difference)?

**Comment by dentoir** [comment] 2016-05-27 08:52
To further summarize the current issue from the capturing and storage perspective.

- A custom timezone is set in config.php, by default is was Europe/London, now UTC
- MySQL uses the system configured time by default.
- Tweets are received in UTC and UTC is inserted in the database (but not as full UTC string, in other words: without explicit timezone in the timestamp)
- So, if the system time is **not** UTC, there will be a discrepancy in what is stored and what isn't. To correct this mistake, we could assume it is UTC anyway, in MySQL language: conver_tz(created_at, 'UTC', 'whateverwewant') should always work.
- The _analysis_ part assumes the timezone as set in config.php.

We need to think about how to streamline/fix this with as little code changes possible. One think we could do is to make sure we insert tweets with the created_at including the UTC timezone. MySQL should then recognize it as UTC and at least we store everything correctly (TEST: some MySQL servers need you to load timezone recognition into the database for this to work: Ubuntu 14.04?). This is a good practice, but has a drawback: historical information currently is inserted into the database as if it were UTC. Which is not always correct, but at least consistent. If we change the way we insert the data, we would lose historical consistency.

**Comment by dentoir** [comment] 2016-05-27 15:41
I removed my summarization, because the comment on #194 is a more precise and more complete description of this issue. Yes, I can confirm this is a bug which no one has noticed before. Real-time tweets are inserted in our servers at this moment with a misinterpretation because of the difference between UTC and London time.

The basic outline of a solution could be:

1. Make the native MySQL convert_tz() function work by following instructions here: http://dev.mysql.com/doc/refman/5.7/en/mysql-tzinfo-to-sql.html
2. Fix the misaligned insertion of new tweets into the database.
3. For existing tweets, PHP could prepare queries such as this:

`$sql = "UPDATE somebin_tweets SET created_at = convert_tz('created_at', 'UTC', '" . date_default_timezone_get() . "')";`

With the above invocation of convert_tz(), I'm swapping source and destination to fix the erroneous conversion. Feedback very welcome. However, I think it will take a long time when executing this query on a bin with 50 million tweets. Additionally it would be wonderful if we didn't need to keep records of which bin was 'fixed' for this issue and which wasn't.

@ekborra In the mean time, I still cannot merge the phrasestable branch because our new tcat_captured_phrases table simply copies the created_at value from the tweets tables and I wanted to discuss the impact of this issue with you first.

**Comment by hoylen** [comment] 2016-05-30 04:45
A script to fix up the `created_at` values for previously captured tweets is definitely a good idea. Since the MySQL `DATETIME` datatype does not carry any timezone information, having that value in anything besides UTC would be very confusing. The above fix is very nice, since it works even if the user didn't realise the disastrous consequences of manually edited the timezone in their _config.php_. Hopefully, no one has changed it more than once, otherwise it will be or impossible (or extremely difficult) to figure out what the correct capture times are supposed to be.

The capture code must take the value provided by Twitter and insert it into the table unchanged. The only manipulation should be via regular expressions or string manipulation; untouched by any date/time functions. That way, it will do exactly the same thing, regardless of what timezones are set (in the operating system, PHP or the [many](http://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html) in MySQL), and regardless of whether any of them are the same/different or correct/incorrect.

Reading out the data and displaying it... that's where timezone manipulation might be useful for displaying in the user's preferred timezone. Perhaps that can be the purpose of setting the PHP timezone in the _config.php_ file?

I don't think programs that read CSV/TSV expects timezones, so they should always come out in UTC.

**Comment by dentoir** [comment] 2016-06-14 09:20
Fixed in master! As will be explained during the upgrade proces, if the TCAT MySQL database user does not have root privileges (which is a generally good idear and the default behaviour in the auto-installer) you will need to import the 'timezone' data in MySQL manually, as explained in the link below. The Debian/Ubuntu oneliner will be presented to the user by the upgrade script.

http://dev.mysql.com/doc/refman/5.6/en/time-zone-support.html

The complexity of the upgrade step has been marked as 'expensive', because it may take quite a while on long-running servers and is blocking to a limited degree (only noticable om very large datasets). This includes gap and ratelimit rebuilds.

Nevertheless running the upgrade step is important and may become mandatory in the future (as we can improve the analytical front-end to use the newly created phrases table to increase performance - issue #206)

We'd appreciate feedback from early upgraders, and/or fixes if anything goes awry.

**Comment by brendam** [comment] 2016-06-14 11:06
What will happen on new installs if the config.php timezone is set to UTC but the mysql time zone support is not configured? Will this cause any problems, or is it only needed for the upgrade process?

**Comment by dentoir** [comment] 2016-06-14 11:25
Currently, it is only needed for the upgrade process, so your installations will function without it. But we may want to use it in the future in the analysis front-end to do timezone conversions. Therefore I've already modified the auto-installer script to automatically install the time zone support on new installations. I've also added it as a recommendation to the wiki.

**Comment by dentoir** [comment] 2016-06-14 13:06
Note a Change log has been added to the wiki and the Test plan (previously inside the repository) has been moved to the wiki as well.

**Comment by hoylen** [comment] 2016-06-15 08:18
I assume the upgrade process is basically using the MySQL _convert_tz_ function to change the _created_at_ values in the database, from incorrect values into correct values in UTC. The incorrect values being wrong because they were changed from UTC into the timezone that was set by _date_default_timezone_set_ in _config.php_.

It seems more correct to be using the timezone conversion functions in PHP to fix the wrong values, than to use the timezone conversion functions in MySQL. Firstly, because the strings used in _date_default_timezone_set_ are from the set of PHP timezone names, which is slightly different from the set of MySQL timezone names. If the user had changed the value in _config.php_ to a value that MySQL does not recognise, the upgrade will not work. Secondly, the PHP timezone information could be different from the MySQL timezone information (e.g. one of them has out of date information on when daylight saving starts/ends). Thirdly, this would avoid the need to import timezone data into MySQL.

With the fix applied, should the _date_default_timezone_set_ be removed from _config.php.example_? Does it do anything? If left in, the user might think it is something to configure.

P.S. I have some functions in the REST API pull request #205 that can be be useful for parsing/displaying PHP DateTime objects with timezones. Tip: don't specify an offset to create a PHP DateTimeZone object: it won't raise an error, but will corrupt DateTime values (it too me a long time to find this bug in PHP).

**Comment by dentoir** [comment] 2016-06-15 09:46
> I assume the upgrade process is basically using the MySQL convert_tz function to change the created_at values in the database, from incorrect values into correct values in UTC. The incorrect values being wrong because they were changed from UTC into the timezone that was set by date_default_timezone_set in config.php.

That is exactly how it works ;-)

> It seems more correct to be using the timezone conversion functions in PHP to fix the wrong values, than to use the timezone conversion functions in MySQL. Firstly, because the strings used in date_default_timezone_set are from the set of PHP timezone names, which is slightly different from the set of MySQL timezone names. If the user had changed the value in config.php to a value that MySQL does not recognise, the upgrade will not work.

Do you have a reference to a discussion on this issue? They should be very similar, because they both use the 'Olson' standard. I suggest a work-around could be to produce a warning whenever the time zone != 'Europe/London'. If the time zone is _not known_ by MySQL, we could require the user to manually verify which MySQL time zone is appropriate. I wonder, though, if that is not a very theoretical situation.

> Secondly, the PHP timezone information could be different from the MySQL timezone information (e.g. one of them has out of date information on when daylight saving starts/ends). Thirdly, this would avoid the need to import timezone data into MySQL.

If you have a reference to such a bug, its possible to blacklist those time zones. But we can't protect the user against all external bugs imho. What happens if the erroneous time zones are dependent on the PHP version the user has?

> 
With the fix applied, should the date_default_timezone_set be removed from config.php.example? Does it do anything? If left in, the user might think it is something to configure.

Yes, this option is now completely ignored and it has been removed from the example file. We should generate a configuration warning if people use it, but we haven't gotten around to it yet.

Regarding your final point, the use of convert_tz(). It is a significant drawback to ask the user to manually execute a sudo instruction, but the function has many advantages, particularly its simplicity and speed. We managed to convert a bin with 80 million tweets in fifteen minutes with it. Consider the case when we would have used PHP, we would need to either 1) update those bins row-by-row because we obviously cannot use PHP datetime functies inline in a MySQL query, which is do-able but will be much slower, or, 2) do some very intelligent segmenting based on daylight saving aspects of all available time zones, which I don't think is feasible.

Having the MySQL time zones in the server may be useful in the future as well.

> P.S. I have some functions in the REST API pull request #205 that can be be useful for parsing/displaying PHP DateTime objects with timezones. Tip: don't specify an offset to create a PHP DateTimeZone object: it won't raise an error, but will corrupt DateTime values (it too me a long time to find this bug in PHP).

Yes, that API code looks very useful, thank you very much. We will have to look at it after the Summer School though unfortunately, which starts in two weeks and takes two weeks, and which is the busiest tiime of the year for us.

**Comment by dentoir** [comment] 2016-10-11 07:48
There have been no new issues reported with this. Closing.

**Closed by dentoir** 2016-10-11 07:48 UTC
Labels: bug
