### ISSUE TITLE
Validate bounding boxes when creating geotrack bins...

### ISSUE THREAD

**Issue by mikesname** [digitalmethodsinitiative/dmi-tcat#260] opened 2017-03-31 09:08 UTC
Currently if you accidentally add a bin with a malformed bounding box, e.g. "51.513586, -0.134843, 51.512915, -0.134594" (second latitude lower than south-west corner), it will cause 406 NotAcceptable errors from the Twitter API. 

It would be nicer if the TCAT did a sanity check on these values before creating a geotrack that will break harvesting.

**Comment by dentoir** [comment] 2017-05-30 14:11
Hi @mikesname,

It's a good idear to try and prevent TCAT from not running those queries. The problem is we cannot do a simple numeric comparison. If the second latitude is lower than the first, like in this example, it means the geo area queries is very huge (covering most of the Earth). The 406 NotAcceptable is thrown for very large areas; I think it is also thrown when querying all tweets from France for example. So if we want to catch these queries from the front-end, we should calculate the area size in PHP and define our own maximum.

**Comment by dentoir** [comment] 2017-05-30 15:01
I've pushed a fix for this issue to the PHP 7 branch, which should be merged into master soon. It currently denies adding huge areas approximately as large as France. The value could be tweaked, though. It should help avoid obvious errors.

**Closed** 2017-09-18 14:38 UTC
Labels: enhancement, feature request
