### ISSUE TITLE
Note field on capture page - (Feature request)

### ISSUE THREAD

**Issue by bornakke** [digitalmethodsinitiative/dmi-tcat#92] opened 2015-02-25 07:39 UTC
Dear DMI,

Using TCAT is becoming more and more popular between STS sociologists here in Copenhagen. This is great except it has led to a number of different people now having access to add new queries and the subsequently effect that we from time to time hits the rate limit of the server. 

Since I'm unaware who initially added a certain query I have currently no way of knowing what queries can be stopped when the limit is hit. I were therefore thinking if it would be possible to add a small 'note' field next to every query in which the person adding the query can add informations such as his or her name and for how long the query are suppose to run?

Best regards
Tobias Bornakke

**Comment by ErikBorra** [comment] 2015-02-26 09:55
Hi @bornakke,

this is a duplicate of issue #64 and relates to issue #61. Adding a note should be straightforward, but it would be more desirable (in my view) to have a proper user authentication and permission scheme. Maybe we should start with the former though ;) We'll try to address it next week.

Best,

Erik

**Comment by ErikBorra** [comment] 2015-03-06 12:13
Implemented in 4100adbfb8750da3e985e711f48f67556dd6a7f7

**Closed** 2015-03-06 12:13 UTC
Labels: feature request
