### ISSUE TITLE
The Dataset Field in analysis page have no queries value

### ISSUE THREAD

**Issue by limogin** [digitalmethodsinitiative/dmi-tcat#214] opened 2016-08-01 07:05 UTC
I have made a recent a fresh installation. In analysis page, in overview of your selection panel, the dataset field have no queries value. But these queries exists and are working well. 
I have a installation in "track" mode.

**Comment by dentoir** [comment] 2016-08-01 07:58
Hi @limogin 

Can you give us a dump of your PHP/Apache error log, usually /var/log/apache2/error.log

Cheers,

Emile

**Comment by limogin** [comment] 2016-08-01 08:53
Hi Emile, 

I paste here, I only see php notices for deprecated functions:

```
[Mon Aug 01 10:48:37.694438 2016] [:error] [pid 1459] [client 37.14.184.84:47477] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 897
[Mon Aug 01 10:48:37.695528 2016] [:error] [pid 1459] [client 37.14.184.84:47477] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/dmi-tcat/analysis/common/functions.php on line 897

```
Thanks for your attention, 

Victor

**Comment by dentoir** [comment] 2016-08-02 13:35
Hi @limogin 

And ofcourse, when you visit the capture/ panel you do see the proper bin names? Are you using irregular characters in your bin names? Can you maybe provide a screen shot (of both pages) to see if their may be something unusual there?

**Comment by limogin** [comment] 2016-08-04 05:02
Hi @dentoir,

I understand that I have the information set correctly. I am not aware using words with special characters. I attach these screenshots. 

![capture-keyword-sample](https://cloud.githubusercontent.com/assets/457811/17390857/26c6f8da-5a11-11e6-89ed-1dbc36c37f22.png)
![analysis-select-dataset](https://cloud.githubusercontent.com/assets/457811/17390860/2a0ec4c8-5a11-11e6-9f53-ba62fb4031fb.png)

Regards, 

Victor.

**Comment by dentoir** [comment] 2016-08-04 06:55
HI @limogin 

From your screenshot it looks your installation is working well - capturing _and_ overview. I guess I don't understand your question.

The 'query' value in analysis empty is because you did not specify what to look for inside your dataset. The TCAT wiki documentation explains the different types of analysis you can do.

**Comment by ErikBorra** [comment] 2016-08-04 08:24
@dentoir, in between the brackets next to the data set name (above the selection) there should be a list of queries.

**Comment by limogin** [comment] 2016-08-04 09:06
My MySQL release is:
```

mysql> select @@version;
+-----------------+
| @@version       |
+-----------------+
| 5.5.50-0+deb8u1 |
+-----------------+
1 row in set (0.00 sec)
```

**Comment by dentoir** [comment] 2016-08-04 09:11
Hi @limogin 

This seems to be a new bug, I can reproduce it locally. Thank you for this report. I can fix this today.

**Comment by dentoir** [comment] 2016-08-04 09:21
I believe this is fixed now, can you pull and retry?

**Comment by limogin** [comment] 2016-08-04 10:16
Hi @dentoir. 

Perfect, thanks. It seems to work properly. :) 

![analysis](https://cloud.githubusercontent.com/assets/457811/17398436/1b6aa1ae-5a3d-11e6-9eee-0528eeeeae3d.png)

Thanks for your attention, 

Victor.

**Closed** 2016-08-04 10:23 UTC
Labels: bug
