### ISSUE TITLE
Two DMI-TCAT to Gephi Errors

### ISSUE THREAD

**Issue by thmunson** [digitalmethodsinitiative/dmi-tcat#243] opened 2016-11-22 04:03 UTC
Hi,

First, when I export **Social graph by in_reply_to_status_id** from DMI-TCAT, I get the following error when I try to import it into Gephi 9.1:

![screen shot 2016-11-21 at 10 54 53 pm](https://cloud.githubusercontent.com/assets/19197667/20510365/9d807e56-b03d-11e6-8543-5b879e50fbfd.png)

Second, when I export a **Co-hashtag graph by Top Hashtags**, I'm getting significantly more hashtags than I request. For example, for one archive I select the top 300 hashtags, but when I import into Gephi it is showing 9,852 nodes (I'm assuming each node is a hashtag):

![screen shot 2016-11-21 at 11 00 03 pm](https://cloud.githubusercontent.com/assets/19197667/20510436/511f122e-b03e-11e6-83d2-54b92c4e6908.png)

As a result, I get integer calculation errors:

![screen shot 2016-11-21 at 11 01 21 pm](https://cloud.githubusercontent.com/assets/19197667/20510467/7fe10f40-b03e-11e6-8422-62b5eadeb517.png)

I'm using the most up-to-date version of both Gephi and DMI-TCAT.

Thanks for your help!

Bill

**Comment by dentoir** [comment] 2016-11-29 11:39
Hi @thmunson 

My previous commit fixed your first issue ('deprecated' warning). Gephi 0.9 introduced a new specification for .gexf files. As far as I can see, it does not affect our use of the file format; therefore I've been able to simply bump the version.

Regarding your second question, I think we need to at least update the documentation. All hashtags in your data selection will end up in the gdf file, but they will not have _edges_. In your example, there should only be edges between approximately 300 nodes. I say _approximately_ because if the 300nth most frequent hashtag happens to occur equally frequent as several (or potentially, but unlikely a lot of) other hashtags, those will be included in the network as well.

While studying the code, I did notice an off-by-on error where requesting the top n hashtags actually produced a network with the top n + 1) hashtags. So, the network should have at least a single connected hashtag too many (but not a completely different figure). This has now been fixed.

I can't explain the failed to set integer error message. Can you pull the latest version of the code, try to run the top hashtag query with a small number 'n', say five or ten and if the problem keeps occuring send us the example .gdf file?

Cheers,

Emile

**Comment by thmunson** [comment] 2016-12-09 02:58
Hi Emile,

Thanks for getting back and for looking into these issues.

Regarding the failed to set integer number, it seems this is happening when in the co-hashtag export, the wordfrequency * distinctusersforword = more than the maximum number that Gephi allows for the wordfrequencymultipliedbyuniqueusers. Gephi's max number is 999999999 and often that equation equals numbers significantly larger than that. I'm not sure there is anything you can do on your end; Gephi needs to increase the maximum number.

But, I am now noticing something else odd happening with the co-hashtag export. Sometimes the export results in 0 edges, other times in results in 0 edges and 0 nodes, other times a correct number of nodes and edges. This seems to be governed by the end date of the query bit only for certain archives. 

For example, I have attached two cohashtag files for an archive of the #photography hashtag. The first has an end date of 20161208 the second 20161209. 

20161208 opens as an Undirected graph in Gephi with 5953 nodes and 504 edges.

20161209 opens as a Mixed graph with 7373 nodes and 0 edges.

As of this writing, the archive is archiving tweets on 20161209, so I would hope to be able to add those to the Gephi file. 

Now, this is only happening with certain hashtag archives. I just tried with my #prayforsyria archive and it worked just fine with 20161209 as the end date. But, for #streetart, which I have added to the ZIP file, 12000+ nodes but 0 edges. 

So, very odd.

I'm not sure if you can diagnose just from the files, but any insight you can give is greatly appreciated. I have students doing wonderful work with DMI-TCAT this semester and this has been the only hiccup for just a few of them.

Thanks!
Bill

[cohashtag-files.zip](https://github.com/digitalmethodsinitiative/dmi-tcat/files/641091/cohashtag-files.zip)

**Comment by dentoir** [comment] 2017-01-18 12:00
HI @bill,

Sorry for getting back to this issue so late, but we've been very busy with the DMI winter school. I have a few follow-up questions as I cannot immediatly see what the cause of this issue could be.

When you acccess your #photography archive with the date set to 20161209, are you able to get edges in your co-hashtag export when you select a 'minimum frequency' instead of 'top x', or when you select a smaller top number, say 10?

Can you inspect the PHP error log after you've exported a graph with zero edges. It should often be in a file called /var/log/apache2/error.log on your server? It may be the script chokes on something, but I can't guess on what given your data.

Best,

Emile

**Comment by Bill** [comment] 2017-01-18 15:27
I think Emile's reply was meant for @thmunson not me.

**Comment by dentoir** [comment] 2017-01-18 15:44
Yes! I'm sorry. The dangers of the at-sign ;-)

**Comment by thmunson** [comment] 2017-05-23 13:11
Hi @dentoir,

I'm sorry for the long delay getting back. The semester took over, but now I'm ready to try and get this all fixed, especially because I have to prepare a presentation based on the data in the next week or so. 

Here is the status.

I have 13 archives in one account and none of them are reading the tweets. On the DMI-TCAT analysis page I am told, for example:

Number of tweets:	643.417
Number of distinct users: 120.369

But the graph below reads a flat line at 0. And no tweets are included in any export. Also, when I go to the Capture page, I am able to log in, but the screen is blank.

I took your advice and looked in the error log. Today is May 23 and I have not logged in to the system in a long time. Here is what I get, all errors from May 21. That is, no error is generated when I try to compile the tweets:

```
[Sun May 21 06:35:04.818450 2017] [mpm_prefork:notice] [pid 21581] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.19 configured -- resuming normal operations
[Sun May 21 06:35:04.818465 2017] [core:notice] [pid 21581] AH00094: Command line: '/usr/sbin/apache2'
[Sun May 21 07:52:17.695763 2017] [log_config:warn] [pid 15203] (28)No space left on device: [client 139.162.119.197:51576] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 07:52:17.902322 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 139.162.119.197:51690] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log, referer: http://54.70.85.62:80/
[Sun May 21 08:44:30.122173 2017] [log_config:warn] [pid 15202] (28)No space left on device: [client 80.82.77.33:41504] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 08:44:30.492920 2017] [log_config:warn] [pid 15205] (28)No space left on device: [client 80.82.77.33:42138] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 08:44:30.809331 2017] [log_config:warn] [pid 15206] (28)No space left on device: [client 80.82.77.33:42600] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 08:44:31.130877 2017] [log_config:warn] [pid 15203] (28)No space left on device: [client 80.82.77.33:43030] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:49.185324 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01618: user  not found: /manager/html
[Sun May 21 09:12:49.185410 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:49.646525 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Sun May 21 09:12:49.646623 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:50.067978 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Sun May 21 09:12:50.068086 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:50.488973 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Sun May 21 09:12:50.489073 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:50.894813 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Sun May 21 09:12:50.894928 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:51.302082 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Sun May 21 09:12:51.302166 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:51.692218 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01617: user admin: authentication failure for "/manager/html": Password Mismatch
[Sun May 21 09:12:51.692310 2017] [log_config:warn] [pid 15204] (28)No space left on device: [client 106.14.199.159:49634] AH00646: Error writing to /var/log/apache2/other_vhosts_access.log
[Sun May 21 09:12:52.098299 2017] [auth_basic:error] [pid 15204] [client 106.14.199.159:49634] AH01618: user tomcat not found: /manager/ 
```

I have multiple error logs in the apache2 folder, which I suspect are backups.

I have attached an error log that contains the trouble I was having back in December when I started this thread. There is significantly more in there than in the one above.

I am more than happy to send you privately access info so you can look into what is happening more specifically. 

Thanks, again, for your help.
[error2.log.zip](https://github.com/digitalmethodsinitiative/dmi-tcat/files/1022218/error2.log.zip)

Bill

**Comment by thmunson** [comment] 2017-05-26 02:59
@ErikBorra 

Erik,

Would you have a moment to look at the above issue? I've got to prepare a presentation based on one of the archives next week and would greatly appreciate your insights.

Thanks,
Bill

**Comment by ErikBorra** [comment] 2017-05-28 19:41
Hi @thmunson ,

pardon the late reply, holidays ...

It seems like you are out of disk space. 

What output does `df -h` bring you?

Try freeing disk space (or increasing disk space if you are on a virtual machine).

Best,

Erik

**Comment by thmunson** [comment] 2017-05-30 01:09
Hi @ErikBorra,

Thank you for getting back. I was away, as well, which is why my delay.

Here is what I get:

Filesystem      Size  Used Avail Use% Mounted on
udev            492M   12K  492M   1% /dev
tmpfs           100M  344K   99M   1% /run
/dev/xvda1      7.8G  7.4G     0 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            497M     0  497M   0% /run/shm
none            100M     0  100M   0% /run/user

I see that the xvda1 has 0 available. I would go ahead and remove some of the unneeded archives in the instance to create the necessary space to run the exports, but the Capture page is no longer working. On Firefox, the page is bank. On Chrome I get an error message.

Is there another way to remove the archives other then the web interface?

That is, if you think that will work...

Thanks,
Bill

**Comment by ErikBorra** [comment] 2017-05-30 06:59
Hi Bill,

try `rm /var/www/dmi-tcat/analysis/cache/*` to clear the dmi cache. You will not have been able to capture any new tweets since you ran out of disk space. Try freeing more disk space and expand or add a disk.

Best,

Erik

**Closed by ErikBorra** 2017-05-30 06:59 UTC
Labels: bug, question

**Comment by thmunson** [comment] 2017-05-30 21:04
Hi Erik,

Thanks for getting back.

I tried that, but am getting a permissions error. I tried

chmod 755 /var/www/dmi-tcat/analysis/cache/*

But I got an "Operation not permitted" error.

Thanks,
Bill

**Comment by ErikBorra** [comment] 2017-05-31 07:45
Dear Bill,

although we are happy to help fixing issues with the software, we are not a helpdesk. DMI-TCAT is released as open-source software, 'as is', and is maintained by us for the academic community. The questions you are asking concern basic linux administration and are not something with which we can help you. I'd suggest to try to find somebody close to you who was knowledge of linux administration.

Best,

Erik

ps: as the cache dir is now owned by root, apache will not be able to write to the cache dir.

**Comment by thmunson** [comment] 2017-05-31 13:40
Hi Erik,

Thanks for getting back. It has been my understanding that when the tweets are not appearing and the pages are not showing up (as the capture page has not) that it is an issue with the software.

I have been a strong advocate for DMI-TCAT within my portion of the academic community and have successfully taught 18 undergrads how to use the software, as well. I'm in the middle of writing an article advocating for its use over all other archiving systems. I just need to get this archive working because I'm also in the middle of a presentation and the tweets in it form the basis of the article.

I realize you are not a help desk and have spent a lot of time exploring possible solutions prior to contacting you.

Thank you, again,

Bill

PS I changed the owner and group owner back to TCAT and now get a "cannot connect error" and the Capture page is still not appearing.

**Comment by ErikBorra** [comment] 2017-06-01 08:48
Hi Bill,

we have added some extra diagnostic tips to https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Bug-submission-guidelines#is-your-server-functioning-properly

Hope this helps,

Erik

**Comment by ErikBorra** [comment] 2017-06-09 07:30
Hey Bill,

did the diagnostic tips help solving your issue?

Best,

Erik

**Comment by thmunson** [comment] 2017-06-09 09:34
Hi Erik,

Thank you for checking in.

No, unfortunately, I was not able to fix the issue using the very helpful tips page. 

I tried restarting MySQL and Apache2 and though I was able to restart Apache2 I was unable to restart MySQL. I suspected the problem was related to memory, so I found 7MB of error logs I could remove, but that didn't seem to help. I tried to remove some of the databases that I don't need, but I don't have the necessary password to do that.

So, I'm still at a loss, especially why the capture page isn't showing. Seeing that would allow me to delete the databases and free up much needed room. 

Best,
Bill

**Comment by ErikBorra** [comment] 2017-06-09 09:37
Hi Bill,

have you verified that your mysql tables are not corrupted and tried a mysql repair?

Best,

Erik

**Comment by thmunson** [comment] 2017-06-09 13:35
HI Erik,

It seems to be getting hung up in the middle of checking:

```
ubuntu@ip-172-31-24-140:~$ sudo -s
root@ip-172-31-24-140:~# mysqlcheck -A
twittercapture.Climate_Change_hashtags             OK
twittercapture.Climate_Change_media                OK
twittercapture.Climate_Change_mentions             OK
twittercapture.Climate_Change_places               OK
twittercapture.Climate_Change_tweets               OK
twittercapture.Climate_Change_urls                 OK
twittercapture.Climate_Change_withheld             OK
twittercapture.Gotham_hashtags                     OK
twittercapture.Gotham_media                        OK
twittercapture.Gotham_mentions                     OK
twittercapture.Gotham_places                       OK
twittercapture.Gotham_tweets                       OK
twittercapture.Gotham_urls                         OK
twittercapture.Gotham_withheld                     OK
twittercapture.Harambe_hashtags                    OK
twittercapture.Harambe_media                       OK
twittercapture.Harambe_mentions                    OK
twittercapture.Harambe_places                      OK
twittercapture.Harambe_tweets                      OK
twittercapture.Harambe_urls                        OK
twittercapture.Harambe_withheld                    OK
twittercapture.Not_okay_hashtags                   OK
twittercapture.Not_okay_media                      OK
twittercapture.Not_okay_mentions                   OK
twittercapture.Not_okay_places                     OK
twittercapture.Not_okay_tweets                     OK
twittercapture.Not_okay_urls                       OK
twittercapture.Not_okay_withheld                   OK
twittercapture.Photography_2_hashtags
warning  : 1 client is using or hasn't closed the table properly
status   : OK
twittercapture.Photography_2_media
warning  : 1 client is using or hasn't closed the table properly
status   : OK
twittercapture.Photography_2_mentions
warning  : 1 client is using or hasn't closed the table properly
status   : OK
twittercapture.Photography_2_places
warning  : 1 client is using or hasn't closed the table properly
status   : OK
```
I'm fairly certain there are more archives than listed and it did nothing after that.

Bill

**Comment by dentoir** [comment] 2017-06-09 13:59
Hi @Bill,

This is possibly a locking issue. You are trying to repair a table which TCAT is trying to insert data into. I'd suggest the following:

 * Stop cron, as root: `systemctl stop cron`
 * Kill all tcat processes, as root: `pkill tcat`
 * Stop mysql, as root: `systemctl stop mysql`
 * Now manually perform a MyISAM table repair, as root. Head to /var/lib/mysql/twittercapture and issue `myisamchk *.MYI`

Directories above are Debian/Ubuntu defaults, but may vary with operating system. If your myisamchk fails as well (possible with huge tables), please read the documentation for setting different memory limits (https://dev.mysql.com/doc/refman/5.7/en/myisamchk.html).

When all is repaired:

 * `systemctl start mysql`
 * `systemctl start cron`

Hope this helps.

Emile

**Comment by thmunson** [comment] 2017-06-09 14:49
Hi Emile,

Thanks for all that information.

I was able to complete all of that, though I get an error when trying to start mysql. 

I though I should check the error log to see if there was anything about not starting, but when I went to /var/lib/mysql/ in my FTP program, I get an error:

![screen shot 2017-06-09 at 10 48 57 am](https://user-images.githubusercontent.com/19197667/26980836-5391c384-4d01-11e7-8bca-594863baf75a.png)

Does this mean mysql is no longer installed?

Thanks, Bill

**Comment by dentoir** [comment] 2017-06-09 15:07
Hi @thmunson 

It shouldn't; a normal FTP user normally can't access /var/lib/mysql
As a shell user, as root, check on the server status: `systemctl status mysql.service`

Normally, the command `systemctl start mysql` should start the server again. If this does not happen, inspect `/var/log/mysql/errror.log` and the output from the command mentioned above. If the start command doesn't work, you may try a server reboot.

Best,

Emile

**Comment by thmunson** [comment] 2017-06-09 16:19
Hi Emile,

Here is what I get after I rebooted the server:

```
root@ip-172-31-24-140:~# systemctl status mysql.service
systemctl: command not found
root@ip-172-31-24-140:~# status mysql.service
status: Unknown job: mysql.service
```

Thanks,
Bill
