### ISSUE TITLE
GEXF compatible with SIGMAJS?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#146] opened 2016-01-08 20:13 UTC
Hi, im trying to view a exported gexf from dmi-tcat in sigmajs,  but i got this error:

```gexf-parser.js:205 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null```

LINE 205: ```root: xml.getElementsByTagName('gexf')[0], ```

Any idea how to proper view gexf exported?

Regards!

**Comment by ErikBorra** [comment] 2016-01-09 09:22
Hi Patricia,

can you open the gexf in Gephi? Also, can you attach the gexf file to this issue?

Thanks,

Erik

**Comment by psegovias** [comment] 2016-01-11 14:07
Yes i can open in gephi without problem.


[TEST-20160111-20160111--------interactionGraph-min-4-nodes-45cd6cf41f.gexf.zip](https://github.com/digitalmethodsinitiative/dmi-tcat/files/85839/TEST-20160111-20160111--------interactionGraph-min-4-nodes-45cd6cf41f.gexf.zip)

**Comment by psegovias** [comment] 2016-01-13 15:52
Any news?

**Comment by ErikBorra** [comment] 2016-01-13 16:14
Hi @psegovias,

maybe you could try opening the file in Gephi, re-exporting it from Gephi as GEXF, and than open it in Sigma.js. If that works, I can compare the results and see where the file generated by TCAT is different. If that doesn't work, we'll have to open an issue at https://github.com/jacomyal/sigma.js/issues and ask them what's wrong :)

Best,

Erik

**Comment by psegovias** [comment] 2016-01-14 12:15
Well, doenst work when export the same gexf from tcat => gephi => sigmajs

I open the gexf with text compare and  are too many lines differents.

![captura de pantalla 2016-01-14 a las 9 14 07 a m](https://cloud.githubusercontent.com/assets/5105474/12324126/4f9d5ff4-ba9f-11e5-8511-1c94aaee6545.png)


This is the exported from gephi:

[Untitled.gexf.zip](https://github.com/digitalmethodsinitiative/dmi-tcat/files/90345/Untitled.gexf.zip)

**Comment by ErikBorra** [comment] 2016-01-14 12:49
Then I'd suggest you open an issue at the sigma.js issue tracker.

**Comment by ErikBorra** [comment] 2016-01-20 09:02
Hi @psegovias,

have you opened an issue at the sigma.js github?

Best,

Erik

**Comment by psegovias** [comment] 2016-02-05 16:16
yes, but no response at this moment:

https://github.com/jacomyal/sigma.js/issues/700

**Comment by dentoir** [comment] 2016-03-01 14:46
From the remote thread I'm seeing the issue is recognized as a bug in SIGMAJS now, so I'm closing this issue for now.

**Closed by dentoir** 2016-03-01 14:46 UTC
Labels: question
