### ISSUE TITLE
Capture stopping

### ISSUE THREAD

**Issue by jamestripp** [digitalmethodsinitiative/dmi-tcat#302] opened 2018-02-06 10:43 UTC
Good morning,

I'm running TCAT on Ubuntu 15:10. I have a bin running and suddenly it just stops. To restart the capture I need to run the dmitcat_track.php script for a few minutes and then the controller.php. I coudln't find anythign of use in either the controller.log or track.error.log.

Is this something that tends to happen? The tracking has stopped a few times this week.

Best,

James

**Comment by dentoir** [comment] 2018-02-06 11:13
Hi @jamestripp 

Not normally, perhaps this has to do with your network connectivity being interrupted. If your error logs are empty, it usually means the tracking script is hanging on I/O. How long have you been running this instance? Can you verify your system clock time is correct? Can you try to `ping api.twitter.com` for a while from your server and see if there is packet loss?

**Comment by dentoir** [comment] 2018-02-06 11:14
Also don't forget to look at the other error logs, such as from Apache and MySQL.

**Comment by jamestripp** [comment] 2018-02-06 13:48
Hi @dentoir 

Thanks for your quick response. I've been running this instance over the past year and have only had this issue over the past month.

Pinging api.twitter.com shows 0% packet loss on a few hundred packets. The MySQL and Apache2 error logs show nothing out of the ordinary.

I'm not sure what to do next.

Thanks again,

James

**Comment by dentoir** [comment] 2018-02-06 14:16
Hi @jamestripp 

First, do use see messages in `dmesg` (as root) as this may indicate problems as well.

Otherwise, this is somewhat tricky and requires command-line tools, but what I would try next are the following steps. I'm not sure what (Linux) OS you are on though?

Install the `strace` package.

Whenever track is running again (started via controller), mark it's PID (with the `ps -aux` command) and, as root, issue the following command `strace -p PID` where PID is the number of the process. You will see a lot of messages indicating what the process is doing in terms of system calls. You will want to start this process inside a screen (with `screen`) so you can detach from it. Once the capture has stopped re-attach to this screen and report the last hundred lines back. This may hint to what went wrong.rr
Alternatively, you can just wait till the capture is hanging and then do the `strace -p PID`. Now, I'm **assuming** the track process is still alive, right? I'm interested in whether it is still outputting data or not. I've experienced a deep hanging state when I was tunneling the outgoing TCP/IP connection and the network connection was temporarily dropped. The script went unkillable and strace gave zero output.

**Comment by jamestripp** [comment] 2018-02-06 14:41
Hi @dentoir 

Nothing obvious in dmesg. I'm running strace and will attach the output when the data collection stops. Hmm, I'm not sure if the process is still alive or not. 

Shall report back. Thanks for your help!

Best,

James

**Comment by jamestripp** [comment] 2018-02-09 15:36
Hi @dentoir ,

The data capture went down last night. The output of the trace command (what was left in the buffer from screen) is attached.
[strace.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/1711514/strace.txt)

When I logged back in a new process called controller.php had started. Running strace on this process displayed 'wait4(processid,' where processid is was an ID different from the individual. Then the process died for some reason and showed a similiar output as the other process.

I'm not entirely sure what to do next. I'll restart controller.php to get continue collecting the data. Though I'm unsure how to interpret the output of strace.

Best,

James

**Comment by dentoir** [comment] 2018-02-13 10:07
Hi @jamestripp 

Controller.php is started every minute by cron to start the actual tracking process called `dmitcat_track.php`. So the controller process dying is expected behavior. You shouldn't normally start the tracking process by hand because the controller may interfere with it. Did you do a manual install or did you use the auto installer?

Can you verify the posix and pcntl modules are loaded in PHP? They should be listed in the output of `php -m` on the command-line. If not, that might by a problem.

From the strace it appears track is trying to quit, but apparently fails. You say track.error.log is not relevant? Can you still display the content right before a restart?

What I would suggest now is, as root, removing all PID files and content under `proc/` ; making sure that directory is writable to the tracking user (perhaps just use the command: `chmod 777 proc`), kill all TCAT processes and wait for the controller (via cron) to start your tracking process. If the tracking process then hangs again this issue is very problematic to debug and most likely network related.

Best,

Emile

**Comment by jamestripp** [comment] 2018-02-13 10:25
Hi @dentoir ,

The PHP modules are there and thanks for pointing that out about controller.php.

The track.error.log reports and error starting '2018-01-24 18:21:59     stream stopped - error tmhOAuth::__set_state'. I misread the log before. I understand this is something to do with authenticating the api query with twitter, but I'm not sure the exact error and how to fix it. Do you have any ideas?

I've also removed the PID files under proc/ and checked that it is writable by the user, etc.

Best,

James

**Comment by dentoir** [comment] 2018-02-13 15:56
Hi @jamestripp 

Is that the only line in track.error.log before the restart?

**Comment by ErikBorra** [comment] 2018-02-15 13:27
Is your system clock time correct? The Twitter API denies requests from machines which have an improperly configured clock. Check the date with the date command. To sync the server time automatically, install a tool like ntp to keep your system clock synchronized.

**Comment by jamestripp** [comment] 2018-02-15 13:30
Hi Eric,

Thanks for replying. 

It looks like my time is correct. 

 james@x:/var/www/dmi-tcat/capture/stream$ timedatectl
      Local time: Thu 2018-02-15 13:28:34 GMT
  Universal time: Thu 2018-02-15 13:28:34 UTC
        RTC time: Thu 2018-02-15 13:28:34
       Time zone: Europe/London (GMT, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by jamestripp** [comment] 2018-04-01 08:42
Hi everyone,

The error is still occurring. I had a brand new TCAT install on ubuntu 16 and an older install on ubuntu 15 stop collecting on Friday due to the same error. Both happened at the same time. Does this sound like a Twitter or Authentication library issue? The network team have checked and there's been nothing unusual on their end.

Best,

James

**Comment by dentoir** [comment] 2019-06-11 14:30
I'm closing this issue, I can't debug it. I assume this is network related.

**Closed by dentoir** 2019-06-11 14:30 UTC
