### ISSUE TITLE
No data being saved from queries?

### ISSUE THREAD

**Issue by mhockenhull** [digitalmethodsinitiative/dmi-tcat#141] opened 2015-12-01 09:26 UTC
Hi all, 

Hope you can help us with this weird issue, apologies for the lack of documentation. @bornakke can provide logs from the server if neccessary. 

We are running the newest edition of TCAT, have checked that our mysql database is running and have restarted TCAT a couple of times, but we are not getting any data down from the queries we are running. 

Do you have any idea what the problem could be? Thanks for your help!

**Comment by ErikBorra** [comment] 2015-12-01 11:08
Hi @mhockenhull,

that is weird indeed. We have five machines capturing without problems on the latest edition of TCAT. Are you sure that you have an internet connection on the TCAT machine? If so, what do the logs (especially track.log) mention?

Best,

Erik

**Comment by bornakke** [comment] 2015-12-01 11:23
track.error.log have grown to extreme 300 mb (indicating some kind of error). It can be accessed here if you want to take a look at it here:
https://www.dropbox.com/s/jvqz8xmj5pl1luo/track.error.log?dl=0

Controller log also looks a bit puzzeling to me, but I'm unable to make any sense. 
[...]
2015-12-01 10:16:01     script track was not running - starting
2015-12-01 10:17:01     script track was not running - starting
2015-12-01 10:18:01     script track was not running - starting
2015-12-01 10:19:01     script track was not running - starting
2015-12-01 10:20:01     script track was not running - starting
2015-12-01 10:21:01     script track was not running - starting
2015-12-01 10:22:01     script track was not running - starting
2015-12-01 10:23:02     script track was not running - starting
2015-12-01 10:24:01     script track was not running - starting
2015-12-01 10:25:01     script track was not running - starting
2015-12-01 10:26:01     script track was not running - starting
2015-12-01 10:27:01     script track was not running - starting
2015-12-01 10:28:01     script track was not running - starting
2015-12-01 10:29:01     script track was not running - starting
2015-12-01 10:30:01     script track was not running - starting
2015-12-01 10:31:01     script track was not running - starting
2015-12-01 10:32:01     script track was not running - starting
2015-12-01 10:33:01     script track was not running - starting
2015-12-01 10:34:01     script track was not running - starting
2015-12-01 10:35:01     script track was not running - starting
2015-12-01 10:36:01     script track was not running - starting
2015-12-01 10:37:01     script track was not running - starting
2015-12-01 10:38:01     script track was not running - starting
2015-12-01 10:39:01     script track was not running - starting
2015-12-01 10:40:01     script track was not running - starting
2015-12-01 10:41:02     script track was not running - starting

If I compare to before we started having problems I can see it use to look like this: 

2015-11-26 06:16:01     script track is running with pid [3472] and has been idle for 0 seconds
2015-11-26 06:17:01     script track is running with pid [3472] and has been idle for 6 seconds
2015-11-26 06:18:01     script track is running with pid [3472] and has been idle for 4 seconds
2015-11-26 06:19:01     script track is running with pid [3472] and has been idle for 4 seconds
2015-11-26 06:20:01     script track is running with pid [3472] and has been idle for 1 seconds
2015-11-26 06:21:01     script track is running with pid [3472] and has been idle for 5 seconds
2015-11-26 06:22:01     script track is running with pid [3472] and has been idle for 4 seconds
2015-11-26 06:23:01     script track is running with pid [3472] and has been idle for 4 seconds
2015-11-26 06:24:01     script track is running with pid [3472] and has been idle for 2 seconds
2015-11-26 06:25:01     script track is running with pid [3472] and has been idle for 2 seconds
2015-11-26 06:26:01     script track is running with pid [3472] and has been idle for 2 seconds

Best
Tobias

**Comment by ErikBorra** [comment] 2015-12-01 11:28
Hi Tobias,

it seems there is a problem with your login credentials. Track.error.log mentions the following repeatedly:
'''
<html>\\n<head>\\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\\n<title>Error 401 Unauthorized</title>
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing \'/1.1/statuses/filter.json\'. Reason:
<pre>    Unauthorized</pre>
</body>
</html>
```

**Comment by bornakke** [comment] 2015-12-01 12:07
Ah. Just to be sure: Will that be the login credentials to twitter?

**Comment by ErikBorra** [comment] 2015-12-01 12:12
It concerns your API keys. See the section "Insert your OAuth API key from Twitter" on https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Install-Guide#config

**Comment by bornakke** [comment] 2015-12-01 20:36
Tried all the keys on another server - all worked.

Filled out a new config.php file from bottom. Everything working. Quite strange since the collection were running smoothly with that specific setup for several weeks up to the error.

... well the important part is that things are now back to normal. Thank you @ErikBorra for helping us out once again.

Best
Tobias

**Comment by bornakke** [comment] 2015-12-01 20:36
@mhockenhull: Could you close the issue?

**Comment by ErikBorra** [comment] 2015-12-01 21:21
@bornakke that is weird indeed, never had that before. Good to hear that the problem is fixed now!

**Closed by ErikBorra** 2015-12-01 21:21 UTC
